language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t eapriala/learning_multi-docker_clienttest -f ./client/Dockerfile.dev ./client 

script:
  - docker run -e CI=true eapriala/learning_multi-docker_clienttest npm run test -- --coverage

after_success:
  - docker build -t eapriala/learning_multi-docker_client ./client
  - docker build -t eapriala/learning_multi-docker_nginx ./nginx
  - docker build -t eapriala/learning_multi-docker_server ./server
  - docker build -t eapriala/learning_multi-docker_worker ./worker
# Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push these images to docker hub
  - docker push eapriala/learning_multi-docker_client
  - docker push eapriala/learning_multi-docker_nginx
  - docker push eapriala/learning_multi-docker_server
  - docker push eapriala/learning_multi-docker_worker
deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "Learning_multi-docker"
  env: "Learningmultidocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-763372964158"
  bucket_path: "Learning_multidocker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY